/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
/**
 *
 * @author Marco y equipo
 */

import Laboratorio.Analisis;
import static Presentacion.NHorasEntrada.fechaActual;
import java.io.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane; 
import javax.swing.JPanel;
/**
 *
 * @author Marco
 */
public class NuevoAnalisis extends javax.swing.JFrame implements Runnable {
String hora,minutos,segundos;
Thread hilo;

    /**
     * Creates new form Nuevo_Analisis
     */
    public NuevoAnalisis() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registro De Nuevo Analisis");
        setIconImage(new ImageIcon (getClass().getResource("/image/iconoanalisis.jpg")).getImage());
        
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/image/fondo21.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, -30, 3000, 681); 
        
        txtfecha.setText(fechaActual());
        
        hilo=new Thread(this);
        hilo.start();
        setVisible(true);
    }
    
     public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual= new Date();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    
    public void run(){
        //while
        Thread current=Thread.currentThread();
        
        while(current==hilo){
            hora();
            txthora.setText(hora+":"+minutos+":"+segundos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        folio = new javax.swing.JLabel();
        txtfolio = new javax.swing.JTextField();
        IdEmpleado = new javax.swing.JLabel();
        txtideg = new javax.swing.JTextField();
        Fecha = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        txtidp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txttbl = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarequerimientos = new javax.swing.JTextArea();
        Requerimiento = new javax.swing.JLabel();
        cbxanalisis = new javax.swing.JComboBox<>();
        Analisis = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        Descuento = new javax.swing.JLabel();
        txtdescuento = new javax.swing.JTextField();
        DescAplicado = new javax.swing.JLabel();
        txtdesaplicado = new javax.swing.JComboBox<>();
        SubTotal = new javax.swing.JLabel();
        btbcalcular = new javax.swing.JButton();
        txtsubtotal = new javax.swing.JTextField();
        SaldoAbonado = new javax.swing.JLabel();
        txtanticipo = new javax.swing.JTextField();
        txtcalcular = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        folio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        folio.setText("Folio");

        IdEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IdEmpleado.setText("Id Empleado/Gerente");

        Fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Fecha.setText("Fecha");

        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hora");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Datos personales");

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Nombre.setText("Id_paciente");

        txttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Edad", "Sexo"
            }
        ));
        jScrollPane2.setViewportView(txttbl);

        txtarequerimientos.setColumns(20);
        txtarequerimientos.setRows(5);
        jScrollPane1.setViewportView(txtarequerimientos);

        Requerimiento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Requerimiento.setText("Requerimientos");

        cbxanalisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pruebas De Embarazo", "Pruebas De Diabetes", "Pruebas De VIH/SIDA", "Pruebas De CardioVasculares" }));
        cbxanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxanalisisActionPerformed(evt);
            }
        });

        Analisis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Analisis.setText("Nombre del analisis");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("ANALISIS");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("TOTALES");

        Precio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Precio.setText("Precio               $");

        Descuento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Descuento.setText("Descuento");

        txtdescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescuentoActionPerformed(evt);
            }
        });

        DescAplicado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DescAplicado.setText("Desc.Aplicado");

        txtdesaplicado.setEditable(true);
        txtdesaplicado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        txtdesaplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesaplicadoActionPerformed(evt);
            }
        });

        SubTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SubTotal.setText("SubTotal          $");

        btbcalcular.setText("Calcular");
        btbcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbcalcularActionPerformed(evt);
            }
        });

        SaldoAbonado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaldoAbonado.setText("Anticipo           $");

        txtcalcular.setText("Calcular");
        txtcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalcularActionPerformed(evt);
            }
        });

        Total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Total.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Analisis)
                                .addGap(18, 18, 18)
                                .addComponent(cbxanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Nombre)
                                            .addGap(183, 183, 183)
                                            .addComponent(Buscar)
                                            .addGap(374, 374, 374))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Precio)
                                        .addComponent(Descuento)
                                        .addComponent(DescAplicado)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SubTotal)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Total)
                                                .addComponent(SaldoAbonado))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdesaplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btbcalcular)
                                        .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtanticipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtcalcular)
                                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtidp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(folio)
                                                    .addGap(27, 27, 27)
                                                    .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(38, 38, 38)
                                            .addComponent(IdEmpleado)))
                                    .addGap(26, 26, 26)
                                    .addComponent(txtideg, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(Fecha)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Regresar)
                        .addGap(396, 396, 396)
                        .addComponent(Guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(Requerimiento)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(folio)
                            .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdEmpleado)
                            .addComponent(txtideg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Fecha)
                                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txtidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Precio)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Descuento)
                            .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescAplicado)
                    .addComponent(txtdesaplicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btbcalcular))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Analisis)
                    .addComponent(cbxanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTotal)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaldoAbonado)
                    .addComponent(txtanticipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtcalcular)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Requerimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Regresar)
                            .addComponent(Guardar))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        if(txtdescuento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtsubtotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtanticipo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txttotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtarequerimientos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtfecha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txthora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtprecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
       /* }else if(cbxanalisis.getSelectedItem().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta precio", "error", JOptionPane.ERROR_MESSAGE);*/
        /*}else if(txtdesaplicado.getSelectItem().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta precio", "error", JOptionPane.ERROR_MESSAGE);*/
        }
        
        else
        { 
        Negocios.Operaciones na=new Negocios.Operaciones();
         
        /*myanalisis.descuento=Double.parseDouble(txtdescuento.getText());
        myanalisis.sub_total=Double.parseDouble(txtsubtotal.getText());
        myanalisis.anticipo=Double.parseDouble(txtanticipo.getText());
        myanalisis.total=Double.parseDouble(txttotal.getText());
        myanalisis.nom_analisis=(String) cbxanalisis.getSelectedItem();
        myanalisis.requerimientos=txtarequerimientos.getText();
        myanalisis.fecha=txtfecha.getText();
        myanalisis.hora=txthora.getText();
        myanalisis.precio=Double.parseDouble(txtprecio.getText());
        myanalisis.descuento_aplicado=(String) txtdesaplicado.getSelectedItem();*/
        
        try{
        if (na.Nuevo_Analisis(txtdescuento, txtsubtotal, txtanticipo, txttotal, cbxanalisis, txtdescuento, txtfecha, txthora, txtprecio, txtdesaplicado) ==true)
            JOptionPane.showMessageDialog(null, "Rgistro de un nuevo analisis fue exitoso ");
        else 
            JOptionPane.showMessageDialog(null, "ERROR hay un problema");
        }
        catch(SQLException e)
            {
              System.out.println(" ERROR " + e.getMessage());       
            }      
        
        txtfolio.setText("");
        txtideg.setText("");
        txtidp.setText("");
        txtdescuento.setText("");
        txtsubtotal.setText("");
        txtanticipo.setText("");
        txttotal.setText("");
        cbxanalisis.setToolTipText("");
        txtarequerimientos.setText("");
        txtfecha.setText("");
        txthora.setText("");
        txtprecio.setText("");
        txtdesaplicado.setToolTipText("");
    }//GEN-LAST:event_GuardarActionPerformed

    }
    private void txtdesaplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesaplicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesaplicadoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        
        if(txtfolio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtideg.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtfecha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txthora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);   
        }else if(txtprecio.getText().isEmpty()){            
            JOptionPane.showMessageDialog(null, "Falta datos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtdescuento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta nombre", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtsubtotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta precio", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txtanticipo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta requerimientos", "error", JOptionPane.ERROR_MESSAGE);
        }else if(txttotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta requerimientos", "error", JOptionPane.ERROR_MESSAGE); 
        }else if(txtarequerimientos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta requerimientos", "error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {    
         Laboratorio.Analisis myanalisis=new Laboratorio.Analisis();
        
         if (myanalisis.Cons_reg_Analisis(Integer.parseInt(txtfolio.getText()))==true)
             JOptionPane.showMessageDialog(null, "Existe!");
         else
             JOptionPane.showMessageDialog(null, "El "+ folio.getText()+ " NO Existe!");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
       Presentacion.Analisis analisis =  new Presentacion.Analisis();
        analisis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void txtcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalcularActionPerformed
        // TODO add your handling code here:
        double sub_total=Double.parseDouble(txtsubtotal.getText());
        double anticipo=Double.parseDouble(txtanticipo.getText());
        
        txttotal.setText(String.valueOf(sub_total-anticipo));
        
    }//GEN-LAST:event_txtcalcularActionPerformed

    private void btbcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbcalcularActionPerformed
        // TODO add your handling code here:
        double precio=Double.parseDouble(txtprecio.getText());
        double descuento=Double.parseDouble(txtdescuento.getText());
        
        txtsubtotal.setText(String.valueOf(precio-(precio*descuento/100)));
    }//GEN-LAST:event_btbcalcularActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void txtdescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescuentoActionPerformed
        // TODO add your handling code her
        txtdescuento.setEnabled(false);
    }//GEN-LAST:event_txtdescuentoActionPerformed

    private void cbxanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxanalisisActionPerformed
        //  Aquí primera regla de negocio:
        
        String numero;
        numero=JOptionPane.showInputDialog("ingrese 1 si cuenta con un permiso y 2 si no cuenta con el permiso");
        
        if(numero==null)
            JOptionPane.showMessageDialog(null, "el registro ha sido canselado");
        else{
        int edad2;
        edad2=Integer.parseInt(numero);
        
        if(edad2==2)
            JOptionPane.showMessageDialog(null, "no debe seguir con el registro");
        else
            JOptionPane.showMessageDialog(null, "puede seguir con el registro");
        }
    }//GEN-LAST:event_cbxanalisisActionPerformed
    
    
     public static String fechaActual(){
         Date fecha=new Date();
         SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
         
         return formatoFecha.format(fecha);
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoAnalisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Analisis;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel DescAplicado;
    private javax.swing.JLabel Descuento;
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel IdEmpleado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precio;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Requerimiento;
    private javax.swing.JLabel SaldoAbonado;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btbcalcular;
    private javax.swing.JComboBox<String> cbxanalisis;
    private javax.swing.JLabel folio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtanticipo;
    private javax.swing.JTextArea txtarequerimientos;
    private javax.swing.JButton txtcalcular;
    private javax.swing.JComboBox<String> txtdesaplicado;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtfolio;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtideg;
    private javax.swing.JTextField txtidp;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTable txttbl;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
